### PR TITLE
Add update test

### PR DESCRIPTION
**Pull request by tomahawk28**
Toward https://github.com/giantswarm/giantswarm/issues/14622

### CODE REVIEW

**Review by rossf7 — APPROVED** [review]
LGTM

**Review by stone-z — APPROVED** [review]
Thanks!

**Comment by stone-z** [comment]
Just noticed in the test logs it looks like the namespace isn't being passed in properly somewhere:
```
{"caller":"github.com/giantswarm/micrologger@v0.4.0/logger.go:53","level":"debug","message":"finding `giantswarm` app in namespace %!q(MISSING)","time":"2020-12-16T08:24:58.219742+00:00"}
{"caller":"github.com/giantswarm/micrologger@v0.4.0/logger.go:53","level":"debug","message":"found `giantswarm` app in namespace %!q(MISSING)","time":"2020-12-16T08:24:58.222253+00:00"}
```

**Comment by tomahawk28** [comment]
@stone-z Thanks for noticing! I already had merged a fix and would bring it into all repos in the next dependabot round.

**Pull request merged**
